name = "Modgeese 2 Client"
author = "Max Caplan"
version = "0.2.2"
pack-format = "packwiz:1.1.2"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c91cdac2a96098194fbd6c74f193a107ef6368e007e759d40eb4810b2a3b831c"

[versions]
forge = "43.2.0"
minecraft = "1.19.2"
