name = "Modgeese 2 Client"
author = "Max Caplan"
version = "0.2.2"
pack-format = "packwiz:1.1.2"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "49c2153a63c215adad1286a94973ad0d648c029442eab878e6aef8d503012e73"

[versions]
forge = "43.2.0"
minecraft = "1.19.2"
