name = "Modgeese 2 Client"
author = "Max Caplan"
version = "0.1.2"
pack-format = "packwiz:1.1.2"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "463c7a9a2f9784fc5e0d33e9221255f9430cf2190dc048f3837e61fbae14358e"

[versions]
forge = "43.2.0"
minecraft = "1.19.2"
