name = "Modgeese 2 Client"
author = "Max Caplan"
version = "0.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5bfde777a15895096e2ebe5acaa8c4c5f8855315e5b16114541b6ecaa2e38214"

[versions]
forge = "43.2.0"
minecraft = "1.19.2"
