name = "Modgeese 2 Client"
author = "Max Caplan"
version = "0.2.4"
pack-format = "packwiz:1.1.2"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "80615ab4314dcc6fcb7396e0f146733eca396329e8b986ba9a5ba6d004297c21"

[versions]
forge = "43.2.0"
minecraft = "1.19.2"
