name = "Modgeese 2 Client"
author = "Max Caplan"
version = "0.2.2"
pack-format = "packwiz:1.1.2"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5c00e0c3a1be3e0e01c67ad49ca9a8577dd30b2c7821c721154654bc96dc889f"

[versions]
forge = "43.2.0"
minecraft = "1.19.2"
