name = "Modgeese 2 Client"
author = "Max Caplan"
version = "0.1.2"
pack-format = "packwiz:1.1.2"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "19faa37fefd55223db65bbb365a70b1617754d9562f0c74f67f11358ced68a76"

[versions]
forge = "43.2.0"
minecraft = "1.19.2"
